version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prd
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres-db-volume:
  static_volume: